version: "3"

services:
  legacy-application:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
    - "5001:80"
    volumes:
    - .:/var/www/jawa

volumes:
  mysql_data: { driver: local }