version: "3"

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/jawa
    links:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jawadb
      MYSQL_USER: jawa
      MYSQL_PASSWORD: jawa
    ports:
      - "3306:3306"
volumes:
  mysql-data: { driver: local }