<?php
namespace Application\Models;

use JAWA\JAWAModel;

class ExampleModel extends JAWAModel
{
    //If entity is mapping books
    public function __construct()
    {
        $this->setColumns([
            'title' => 'VARCHAR(50) NOT NULL DEFAULT \'Some Title\'',
            'author' => 'VARCHAR(50) NOT NULL DEFAULT \'Some Author\'',
            'type' => 'VARCHAR(50) NOT NULL DEFAULT \'Fiction\'',
            'publisher' => 'VARCHAR(50) NOT NULL DEFAULT \'Some Publisher\'',
            'publishDate' => 'TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()',
        ]);

        // To reduce ambiguity in database, each column name in tables should be prefixed with a unique string
        // eg, books table = b_id, b_author...
        // publisher table = p_id, p_location...
        // binding table = bi_id, bi_type...

        // This means there is never a need to specify tables with 'books.id, publisher.id...'
        // This is forced but can be disabled in the env with 'DISABLE_COLUMN_PREFIXING' = true
        $this->setTablePrefix('b_');

        // The tables for all models are also autogenerated in bootstrap.php
        // Run bootstrap.php in console to generate tables
        // If a table name is not specified, the model name will be used
        $this->setTableName('MyTable');
    }
}